### ISSUE TITLE
Error after char creation

### ISSUE THREAD

**Issue by Enryou** [CiaranHagen/MUD-Game#10]
Sam:
got a error :
                                                                              
Register (r) or log in (l).r
Please enter your desired username: r
Please enter a password: r
Please enter the password again: r
Player file not found. Unable to save progress.

Player file not found. Unable to load progress.

—------------------------------------------------------------------------------
Character creation 

Character name: r
What is your race?
You can choose from: orc, dwarf, elf, troll, succubus, gelfling, gockcobbler, shinigami and hickdead.
> elf
What class do you choose? 
You can choose from: ['warrior', 'rogue', 'beggar']
> beggar
beggars are beggars, nothing special .... what did you expect ?

you get a non-existant bonus of +999 on everything,
proficiency in begging and an additional amount of self-pity
Do you wish to choose BEGGAR as your class ? 
[y/n]
> y
Set the stats of your character. 4 different stats, 10 points to give, you know the drill.
How strong are you?: 
> 3
How agile are you?: 
> 3
How would you rate your intelligence?: 
> 2
Are you feeling lucky?: 
> 2
Go and have fun in the dungeons you dumdum, I bet you will have at least one peer down there.
**Traceback (most recent call last):
  File "main.py", line 364, in <module>
    cPlayer, cChar, roomL, npcL = onstart()
  File "main.py", line 137, in onstart
    currentChar = character.newCharacter(charactername, currentPlayer.username)
AttributeError: 'NoneType' object has no attribute 'username'** 
faolin@Enryou:~/gitProjects/MUD-Game/MUDGame$

**Comment by tomhumbert** [comment]
still?

**Comment by Enryou** [comment]
Fixed ...
